allow for future scheduled content to get an alias
zicht/page-bundle pull request #13
Opened 2017-06-28 15:14 UTC by pbergman

2017-06-28 15:49 UTC, muhammedeminakbulut requested changes

2017-06-28 15:49 UTC, muhammedeminakbulut commented on src/Zicht/Bundle/PageBundle/Security/Voter/ScheduledContentVoter.php
> +    protected static function hasCmsAttribute(array $attributes = [])
waarom is dit protected?

2017-06-28 15:49 UTC, muhammedeminakbulut commented on src/Zicht/Bundle/PageBundle/Security/Voter/ScheduledContentVoter.php
> +        if (null !== $from || null !== $till) {
je zou liever hier de inverse van nemen en gelijk eruit kunnen stappen. want deze if statement word hieronder ook al afgevangen in verschillende scenarios.

en zou je meer comments erin willen zetten wat je doet want het is best een lang stuk code en ik heb er moeite mee om het te begrijpen

2017-06-28 15:49 UTC, muhammedeminakbulut commented on src/Zicht/Bundle/PageBundle/Security/Voter/ScheduledContentVoter.php
> +                        $vote = VoterInterface::ACCESS_DENIED;
er komt na elke $vote assigment geen verdere code. Je zou ze allemaal kunnen returnen op dat moment. dat maakt het ook gelijk duidelijk.

2017-06-29 08:09 UTC, pbergman commented on src/Zicht/Bundle/PageBundle/Security/Voter/ScheduledContentVoter.php
> +        if (null !== $from || null !== $till) {
wat lost dat op?

2017-06-30 06:40 UTC, boudewijn-zicht requested changes

2017-06-30 06:40 UTC, boudewijn-zicht commented on src/Zicht/Bundle/PageBundle/Security/Voter/ScheduledContentVoter.php
> +        if (null !== $from || null !== $till) {
De lees en begrijpbaarheid van de code zou er wel op vooruit kunnen gaan met een aantal early returns, bijvoorbeeld de eerste: `if (null === $from && null === $till) { return $vote; // abstain }`

Ik wil wel dit wel aanpassen als je er geen tijd meer voor hebt

2017-06-30 06:40 UTC, boudewijn-zicht commented on src/Zicht/Bundle/PageBundle/Security/Voter/ScheduledContentVoter.php
> +                        $vote = VoterInterface::ACCESS_DENIED;
Smaak.

2017-07-03 07:59 UTC, pbergman commented on src/Zicht/Bundle/PageBundle/Security/Voter/ScheduledContentVoter.php
> +        if (null !== $from || null !== $till) {
leek me ook meer smaak maar heb hem aangepast.

2017-07-05 07:17 UTC, boudewijn-zicht approved these changes

2017-07-05 07:19 UTC, boudewijn-zicht commented on src/Zicht/Bundle/PageBundle/Security/Voter/ScheduledContentVoter.php
> +        if (null !== $from || null !== $till) {
Thanks!

2017-07-05 07:24 UTC, boudewijn-zicht commented
Scrutinizer heeft een probleem met composer, dat kan ik alleen lokaal niet reproduceren (i.e. `composer install` en `./vendor/bin/phpunit` werken beiden prima)

@muhammedeminakbulut kun jij hier even naar kijken?  Hoeft wat mij betreft een merge niet in de weg te zitten, maar als we het kunnen fixen (ik gok een scrutinizer config ergens) is dat wel erg fijn.

2017-08-01 15:07 UTC, merged